name: AlloyCore
options:
  bundleIdPrefix: com.alloycore
  deploymentTarget:
    iOS: "15.0"
  objectVersion: 56

targets:
  AlloyCore:
    type: framework
    platform: iOS
    sources: [AlloyCore]

  TestApp:
    type: application
    platform: iOS
    sources: [TestApp]
    dependencies:
      - target: AlloyCore